### ISSUE TITLE
ImportError: No module named 'cortexutils'

### ISSUE THREAD

**Issue by mathurin68** [TheHive-Project/CortexDocs#11]
New install keep getting this error -

![image](https://user-images.githubusercontent.com/5932961/38586409-93ee573c-3ceb-11e8-8288-beb733d456bc.png)

I've rerun  ' pip install -r requirements.txt'  in the analyzers folder. 

I've gotten this on a couple analyzers now, but this doesn't happen on all of them.  Out of about 5 I'm testing right now the main ones that are giving this error are Onyphe and Censys.  

Here's a snapshot of permissions - 
![image](https://user-images.githubusercontent.com/5932961/38586559-36ff11c8-3cec-11e8-9172-8f6a03b31094.png)

Thanks and holy cow this looks promising!

**Comment by saadkadhi** [comment]
Does `sudo pip install -U cortexutils && sudo pip3 install -U cortexutils` solve the issue?

**Comment by mathurin68** [comment]
Hey!  Thanks for the suggestion, I tried it but still doesn't seem to want to work -- 
![image](https://user-images.githubusercontent.com/5932961/39157608-969c5d7e-4729-11e8-8a67-dda098de16be.png)

**Comment by ainich** [comment]
Same problem:
File "./yara_analyzer.py", line 3, in <module>
    from cortexutils.analyzer import Analyzer
ImportError: No module named cortexutils.analyzer

**Comment by mathurin68** [comment]
I guess I kind of moved on from it.... there seems to be about 83 analyzers in there now so if one doesn't work, just move on and hopefully it gets fixed in the next upgrade

**Comment by 3c7** [comment]
But in order to fix something we need to know what's going wrong there.

You don't have the necessary python dependencies installed. There are multiple reasons why that can happen:
- you haven't installed dependencies mentioned in requirements.txt using `pip install -r requirements.txt` and/or `pip3 install -r requirements.txt`
- you have installed the requirements as user (`pip install --user -r requirements.txt`) but using the analyzer with another user
- you're using an outdated docker container
- you're using python virtual environments which are not activated when running an analyzer using cortex
- your python installation is some kind of messed up

This is everything I can think of at the moment.

**Comment by nadouani** [comment]
No updates for this issue, closing it.

**Comment by Chromares** [comment]
Changing "#!/usr/bin/env python3" to "#!/usr/bin/env python" in analysers' python script helped me.

**Comment by smclinden** [comment]
@Chromares To elaborate, if you have more than one version of Python 3 on your system, the pip Python path may be different than the default path for "python3". Using "alternatives" to set the default Python means that you can remove the explicit reference to "python3" and use "python" instead.
